#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("8087622153:AAG_WgNgNDEQzK0OMz5_28qDSKP3BPiP9us", "")
    API_ID = int(os.environ["API_ID", "24489231"]
    API_HASH = os.environ["API_HASH", "87077f7c5163f59bcdb67b47f1af09aa"]
    AUTH_USERS = "6302749609"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
